# Generated by Django 4.2.5 on 2023-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], max_length=3)),
                ('to_currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], max_length=3)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
