# Generated by Django 4.2.5 on 2023-09-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_alter_converter_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='value',
            field=models.IntegerField(),
        ),
    ]
